name: Java CI Cresco Controller

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'SONATYPE CRED'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package bundle:bundle
      - name: Deploy to Maven
        run: mvn deploy:deploy-file -Dfile=target/controller-1.2-SNAPSHOT.jar -Durl=https://oss.sonatype.org/content/repositories/snapshots -DrepositoryId=ossrh -DpomFile=pom.xml --settings ci-settings.xml -DskipTests=true -B
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}